# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 10 * * 5"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ ${{ matrix.python-version }} == "3.11" ]; then pip install --upgrade coverage; fi
        pip install --upgrade casadi numpy scipy prettytable
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with unittest
      run: |
        if [ ${{ matrix.python-version }} == "3.11" ]
        then
          coverage run -m unittest discover tests
        else
          python -m unittest discover tests
        fi
    - name: Upload coverage to Codecov
      if: matrix.python-version == 3.11
      uses: codecov/codecov-action@v2
